# **11. Einführung pandas**

Das Python-Modul [pandas](https://pandas.pydata.org/docs/user_guide/index.html) macht das Arbeiten mit tabellarischen Daten und großen statistischen Datensätzen einfacher und ist mit Matplotlib und Numpy kompatibel. 
Gegenüber Matplotlib und Numpy bietet pandas einfach zu nutzende Methoden, um Datensätze zu verändern, Daten zu selektieren, neu anzuordnen und zu vereinen. 
Dabei werden Daten ähnlich einer Datenbank betrachtet.

### 1. Import ###

In [1]:
import pandas as pd 
# instaleirte version von pandas anzeigen
print("Pandas version:",pd.__version__)

Pandas version: 2.2.2

### 2. Datenstrukturen ###
- **[Series](https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series)** : Eindimensionales gelabeltes Array

In [2]:
# Beispiel Daten als einfache Liste (andere datentypen (z.b.: ndarray,Dictionary) sind ebenfalls möglich)
Daten = [10, 20, 30, 40, 50]
Label = ['a', 'b', 'c', 'd', 'e']

#Series
serie = pd.Series(Daten,index = Label) 

serie

a    10
b    20
c    30
d    40
e    50
dtype: int64

- **[DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame)** : Zweidimensional, in der Regel für tabellarische Daten geeignet.
- Kann als Anreihung mehrerer Series betrachtet werten, welche über einen zusammengefassten Index verfügen

Erstellung mit einem Dictionary:

In [3]:
# beisptiel Daten als Dictionary (andere sind auch möglich)
Dictionary = {'Name' : ['Großmann','Mezler','Schwindt'],
              'Matr.-Nr.' : [267855,854892,485557],
              'Studiengang' : ['Biologische Chemie','Geotechnologie','Wirtschaftsmathematik'],
              'Abschluss' : ['M.Sc.','B.Sc.','M.Sc.']}
#DataFrame
Tabele = pd.DataFrame(Dictionary)

Tabele

       Name  Matr.-Nr.            Studiengang Abschluss
0  Großmann     267855     Biologische Chemie     M.Sc.
1    Mezler     854892         Geotechnologie     B.Sc.
2  Schwindt     485557  Wirtschaftsmathematik     M.Sc.

Erstellung mit einem Numpy-Array:

In [4]:
#beispiel Daten als nparry
import numpy as np
nparry = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

# Spalten der resultierenden Tabelle
Spalten = ['A','B','C']
#DataFrame
Matrix_Tab = pd.DataFrame(data = nparry, columns = Spalten)

Matrix_Tab

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

### 3. Zugriff und Bearbeitung von Dataframe-Inhalten ###

Der Zugriff auf ein Dataframe und dessen Bearbeitung ist, wie bei den meisten strukturierten Datentypen, über Indizes möglich. 
Ähnlich wie beim Dictionary wird zunächst eine Spalte angegeben, anschließend kann eine Zeile über den Index angegeben werden.

`DataFrame["Spaltenname"][Index]`

In [5]:
Matrix_Tab['A'][1]

np.int64(4)

Eine Indizierung per Tupel ist möglich, wenn die Dataframe-Objekt-Eigenschaft `.loc` verwendet wird. 
Hier können Daten auch direkt Überschreiben werden.

In [6]:
Matrix_Tab.loc['A', 1] = 10
Matrix_Tab

     A    B    C     1
0  1.0  2.0  3.0   NaN
1  4.0  5.0  6.0   NaN
2  7.0  8.0  9.0   NaN
A  NaN  NaN  NaN  10.0

### 4. Arbeiten mit Datensätzen, Hilfreiche Funtionen ###

In [7]:
# erstellen der Beispieldaten 
beispiel_Tabelle = pd.DataFrame(data = np.arange(50).reshape(5,10),
                                columns =['Spalte A','Spalte B','Spalte C','Spalte D','Spalte E','Spalte F','Spalte G','Spalte H','Spalte I','Spalte J'])
beispiel_Tabelle

,Spalte A,Spalte B,Spalte C,Spalte D,Spalte E,Spalte F,Spalte G,Spalte H,Spalte I,Spalte J
0,0,1,2,3,4,5,6,7,8,9
1,10,11,12,13,14,15,16,17,18,19
2,20,21,22,23,24,25,26,27,28,29
3,30,31,32,33,34,35,36,37,38,39
4,40,41,42,43,44,45,46,47,48,49

- **[CSV Datei erstellen](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html)** aus einem DataFrame

In [8]:
beispiel_Tabelle.to_csv('beispiel_Tabelle.csv',index=False) # index=False : zeilen Indexierung wird nicht angefügt

- **[CSV Datei lesen](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv)**

Es können Daten aus verschiedenen Dateiarten eingelesen werden. Unter den unterstützten Dateiarten sind die, die häufig zum Loggen von Daten oder organisieren/Festhalten von Versuchsergebnissen verwendet werden.

In [9]:
csv_beispiel_tabelle_2 = pd.read_csv('beispiel_Tabelle.csv') 
print(type(csv_beispiel_tabelle_2))
csv_beispiel_tabelle_2

<class 'pandas.core.frame.DataFrame'>

,Spalte A,Spalte B,Spalte C,Spalte D,Spalte E,Spalte F,Spalte G,Spalte H,Spalte I,Spalte J
0,0,1,2,3,4,5,6,7,8,9
1,10,11,12,13,14,15,16,17,18,19
2,20,21,22,23,24,25,26,27,28,29
3,30,31,32,33,34,35,36,37,38,39
4,40,41,42,43,44,45,46,47,48,49

**[DataFrame.info](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html)**
- allgemeine Zusammenfassung zu einem DataFrame
- praktisch, um schnell sehen zu können, welche Spalten enthalten sind und welchen Datentyo sie enthalten sowie, ob nicht-definierte Werte enthalten sind

In [10]:
csv_beispiel_tabelle_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Spalte A  5 non-null      int64
 1   Spalte B  5 non-null      int64
 2   Spalte C  5 non-null      int64
 3   Spalte D  5 non-null      int64
 4   Spalte E  5 non-null      int64
 5   Spalte F  5 non-null      int64
 6   Spalte G  5 non-null      int64
 7   Spalte H  5 non-null      int64
 8   Spalte I  5 non-null      int64
 9   Spalte J  5 non-null      int64
dtypes: int64(10)
memory usage: 528.0 bytes

- **[DataFrame.size](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.size.html)**

In [11]:
csv_beispiel_tabelle_2.size # gibt die Anzahl der Einträge (in den Zeilen und Spalten ohne die Zeilen und Spalten selbst) zurück

50

In [12]:
csv_beispiel_tabelle_2.columns #gibt die Spalten zurück

Index(['Spalte A', 'Spalte B', 'Spalte C', 'Spalte D', 'Spalte E', 'Spalte F',
       'Spalte G', 'Spalte H', 'Spalte I', 'Spalte J'],
      dtype='object')

- **[DataFrame.shape](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.shape.html)**

In [13]:
csv_beispiel_tabelle_2.shape #gibt ein tupel der Größe des DataFrames zurück

(5, 10)

- **[DataFrame.head](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html)**

In [14]:
n=4
csv_beispiel_tabelle_2.head(n) # gibt die n. Zeile von "oben gezählt" zurück

,Spalte A,Spalte B,Spalte C,Spalte D,Spalte E,Spalte F,Spalte G,Spalte H,Spalte I,Spalte J
0,0,1,2,3,4,5,6,7,8,9
1,10,11,12,13,14,15,16,17,18,19
2,20,21,22,23,24,25,26,27,28,29
3,30,31,32,33,34,35,36,37,38,39

- **[DataFrame.tail](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.tail.html)**

In [15]:
n=3
csv_beispiel_tabelle_2.tail(n) # gibt die n. Zeile von "unten gezählt" zurück

,Spalte A,Spalte B,Spalte C,Spalte D,Spalte E,Spalte F,Spalte G,Spalte H,Spalte I,Spalte J
2,20,21,22,23,24,25,26,27,28,29
3,30,31,32,33,34,35,36,37,38,39
4,40,41,42,43,44,45,46,47,48,49

- **[DataFrame.at](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.at.html)** : Hilfreich um einen Wert auszuwählen

In [16]:
csv_beispiel_tabelle_2.at[1,'Spalte A']

np.int64(10)

**[DataFrame.loc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html)**
- hilfreich zum zugreifen auf Datengruppen über die Namen der Zeilen / Spalten
- Die Zeilen und Spalten stellen hier keys dar, über die wir auf die Werte zugreifen können

In [17]:
csv_beispiel_tabelle_2.loc[[1,2]] # gibt die 2. und 3. zeile aus

,Spalte A,Spalte B,Spalte C,Spalte D,Spalte E,Spalte F,Spalte G,Spalte H,Spalte I,Spalte J
1,10,11,12,13,14,15,16,17,18,19
2,20,21,22,23,24,25,26,27,28,29

- Indizierung ähnlich wie bei Numpy-Arrays möglich, jedoch sind hier die Grenzen *inklusive*!

In [18]:
csv_beispiel_tabelle_2.loc[1 : 2 , 'Spalte B' : 'Spalte D'] # Schneidet / sliced einen Teil der Tabelle aus

   Spalte B  Spalte C  Spalte D
1        11        12        13
2        21        22        23

`.loc` ist praktisch, wenn man zum beispiel mehrere werte überschreiben möchte.

In [19]:
Spalte_B_weniger_20 = csv_beispiel_tabelle_2['Spalte B'] < 20
print(Spalte_B_weniger_20,"# eine Series von Spalte B mit datentyp bool")
print(Spalte_B_weniger_20.shape)
csv_beispiel_tabelle_2.loc[Spalte_B_weniger_20,'Spalte B'] = 0
csv_beispiel_tabelle_2

0     True
1     True
2    False
3    False
4    False
Name: Spalte B, dtype: bool # eine Series von Spalte B mit datentyp bool
(5,)

,Spalte A,Spalte B,Spalte C,Spalte D,Spalte E,Spalte F,Spalte G,Spalte H,Spalte I,Spalte J
0,0,0,2,3,4,5,6,7,8,9
1,10,0,12,13,14,15,16,17,18,19
2,20,21,22,23,24,25,26,27,28,29
3,30,31,32,33,34,35,36,37,38,39
4,40,41,42,43,44,45,46,47,48,49

Zu beachten ist, dass mehrdimensionale Keys nicht übergeben werden können, da hiermit die Zuordnung der Zeilen / Series nicht mehr eindeutig wäre.

In [20]:
gerade_werte = csv_beispiel_tabelle_2 % 2 == 0

print(gerade_werte)
#csv_beispiel_tabelle_2.loc[gerade_werte] #### Auskommentierung entfernen, um Fehler-Meldung zu sehen

   Spalte A  Spalte B  Spalte C  Spalte D  Spalte E  Spalte F  Spalte G  \
0      True      True      True     False      True     False      True
1      True      True      True     False      True     False      True
2      True     False      True     False      True     False      True
3      True     False      True     False      True     False      True
4      True     False      True     False      True     False      True

   Spalte H  Spalte I  Spalte J
0     False      True     False
1     False      True     False
2     False      True     False
3     False      True     False
4     False      True     False

- **[DataFrame.iloc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html)** : wie .loc, nur über Integer-Indizes

In [21]:
csv_beispiel_tabelle_2.iloc[[1,2],[1,2,3]] # mithilfe in integer listen

   Spalte B  Spalte C  Spalte D
1         0        12        13
2        21        22        23

In [22]:
csv_beispiel_tabelle_2.iloc[1:3,1:4] # mithilfe von array objecten

   Spalte B  Spalte C  Spalte D
1         0        12        13
2        21        22        23

- **[DataFrame.insert](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.insert.html)** : fügt eine Spalte hinzu

In [23]:
csv_beispiel_tabelle_2.insert(10,'Spalte K',[100,200,300,400,500]) # gibt einen fehler aus Wenn die Spalte bereits existiert 
csv_beispiel_tabelle_2

,Spalte A,Spalte B,Spalte C,Spalte D,Spalte E,Spalte F,Spalte G,Spalte H,Spalte I,Spalte J,Spalte K
0,0,0,2,3,4,5,6,7,8,9,100
1,10,0,12,13,14,15,16,17,18,19,200
2,20,21,22,23,24,25,26,27,28,29,300
3,30,31,32,33,34,35,36,37,38,39,400
4,40,41,42,43,44,45,46,47,48,49,500

Eine neue Spalte kann auch "direkt" erstellt werden:

In [24]:
csv_beispiel_tabelle_2["Spalte J+K"] = csv_beispiel_tabelle_2['Spalte J'] + csv_beispiel_tabelle_2['Spalte K']
csv_beispiel_tabelle_2

,Spalte A,Spalte B,Spalte C,Spalte D,Spalte E,Spalte F,Spalte G,Spalte H,Spalte I,Spalte J,Spalte K,Spalte J+K
0,0,0,2,3,4,5,6,7,8,9,100,109
1,10,0,12,13,14,15,16,17,18,19,200,219
2,20,21,22,23,24,25,26,27,28,29,300,329
3,30,31,32,33,34,35,36,37,38,39,400,439
4,40,41,42,43,44,45,46,47,48,49,500,549